### PR TITLE
add bidirectional sync as an option

### PR DESCRIPTION
**Pull request by NL-TCH**
this will create an extra toggle to set bisync instead of copy, fix mentioned in #2

### CODE REVIEW

**Comment by GedasFX** [comment]
Was this confirmed to work on conflicting files? I remember hearing some issues. For example if you update files locally and remotely you may get some form of error

**Comment by NL-TCH** [comment]
there are examples how rsync bisync synchronizes: https://rclone.org/bisync/#normal-sync-checks
for conflicts, look at the second line: https://rclone.org/bisync/#safety-measures

note: i have not tested conflicts

**Comment by GedasFX** [comment]
Yeah this is what I am worried about, this might be way too confusing for people, and I don't really want to be tech support for this sadly.

When people see bidirectional sync I think they would expect to see a warning saying this will cause issues, instead of needing to go to file system and then manually resolve.

**Comment by NL-TCH** [comment]
yeah fair enough, can you at least publish this as a preview of the plugin, so users who want/understand it can use it?

**Comment by GedasFX** [comment]
Would it be okay to have it as a hidden feature flag first? Instead of having a toggle front and center, just have a text field in plugin.properties?

**Comment by NL-TCH** [comment]
yeah sounds good, can it be a feature flag, that enables the front-end switch, i want to be able to switch between bisync and copy from the GUI

so, feature flag -> enables GUI switch -> enables the possibility to change between copy and bisync

**Comment by GedasFX** [comment]
Works for me!

**Comment by NL-TCH** [comment]
featureflag added, need to reload steam for the plugin to see the change in the plugin.settings

**Comment by NL-TCH** [comment]
featureflag is: bysinc_visible

**Comment by NL-TCH** [comment]
the variable names to enable the featureflag and to switch between config/bysinc are not very intuitive, feel free to change them :)

**Comment by GedasFX** [comment]
we could do something like `bisync_enabled` and `bisync_visible`. Then we bump the minor version in package.json and then we could push release.

Could you do these changes?

**Comment by NL-TCH** [comment]
experimental_features

instead of bisync_visible the featureflag is 'experimental_menu', if set to 'true' the section above will display (including the warning). This is nice for future experimental features

**Comment by NekoGryphou** [comment]
When the version with this change will be released ? :)

**Comment by GedasFX** [comment]
@NekoGryphou hey, during testing encountered several stability and usability issues, so wasn't comfortable making a release since that would also need to be tested by decky testers and its really not ready for that 😅. I could make a prerelease here on github if you'd like, but I for sure would not recommend using it.

**Comment by NekoGryphou** [comment]
Alright ! 
I can't wait to see this feature so that I can synchronize my saves between my machines via the cloud ! :p

**Pull request merged**
